const fs = require('fs');

let fileContent = fs.readFileSync('src/data/annualDistributionData.ts', 'utf8');

// Strip imports
let cleanContent = fileContent.replace(/import.*?['"].*?['"];/g, '');

const evalStr = cleanContent.replace(/export const ANNUAL_DISTRIBUTIONS[:\s\w\[\]]*=/, 'return');
const arr = new Function(evalStr)();

const filteredArr = arr.filter(item => item.level !== '1am');

const data1am = [
  {
    "id": "1am-w1",
    "level": "1am",
    "trimester": 1,
    "month": "سبتمبر",
    "weekNumber": 1,
    "weekDates": "21-24",
    "midan": "الإنسان والصحة",
    "maqta": "",
    "mawrid": "",
    "learningContent": "- استقبال التلاميذ؛ تعارف وتقويم تشخيصي\n- عرض الوضعية الانطلاقية الشاملة ومناقشتها وطرح التساؤلات حول",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w2",
    "level": "1am",
    "trimester": 1,
    "month": "سبتمبر",
    "weekNumber": 2,
    "weekDates": "27 سبتمبر - 01 أكتوبر",
    "midan": "الإنسان والصحة",
    "maqta": "معالجة بيداغوجية",
    "mawrid": "1 - الكفاءة الأولى: حفظ الصحة\nالمعايير: 3،4",
    "learningContent": "",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w3",
    "level": "1am",
    "trimester": 1,
    "month": "أكتوبر",
    "weekNumber": 3,
    "weekDates": "04-08",
    "midan": "الإنسان والصحة",
    "maqta": "معالجة بيداغوجية",
    "mawrid": "2 - الكفاءة الثانية: حماية المحيط\nالمعايير: 3،4،5",
    "learningContent": "",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w4",
    "level": "1am",
    "trimester": 1,
    "month": "أكتوبر",
    "weekNumber": 4,
    "weekDates": "11-15",
    "midan": "الإنسان والصحة",
    "maqta": "I التغذية عند الإنسان",
    "mawrid": "",
    "learningContent": "- عرض وضعية الانطلاق ومناقشتها",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w5",
    "level": "1am",
    "trimester": 1,
    "month": "أكتوبر",
    "weekNumber": 5,
    "weekDates": "11-15",
    "midan": "الإنسان والصحة",
    "maqta": "I",
    "mawrid": "1 مصدر الأغذية وتركيبها (الغذاء)",
    "learningContent": "1- مصدر الأغذية وتركيبها:\nنشاط 1 يكشف - تجريبيا مصدر الأغذية أو يحلل نتائج تجريبية",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w6",
    "level": "1am",
    "trimester": 1,
    "month": "أكتوبر",
    "weekNumber": 6,
    "weekDates": "18-22",
    "midan": "الإنسان والصحة",
    "maqta": "I",
    "mawrid": "1 مصدر الأغذية وتركيبها",
    "learningContent": "نشاط 2 يقارن - تركيب بعض الأغذية (يكشف تجريبيا مركبات)\nنشاط 3 ينجز - حوصلة لمصدر الأغذية وتركيبها (مخطط تلخيصي أو نص)",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w7",
    "level": "1am",
    "trimester": 1,
    "month": "أكتوبر",
    "weekNumber": 7,
    "weekDates": "25-29",
    "midan": "الإنسان والصحة",
    "maqta": "I",
    "mawrid": "2 دور الأغذية في الجسم",
    "learningContent": "2- دور الأغذية في الجسم:\nنشاط 1 يستخرج - العلاقة بين أعراض بعض أمراض سوء التغذية ومميزات الغذاء المستهلك.\nنشاط 2 يلخص - دور الأغذية في العضوية.",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w8",
    "level": "1am",
    "trimester": 1,
    "month": "أكتوبر",
    "weekNumber": 8,
    "weekDates": "28 أكتوبر - 02 نوفمبر",
    "midan": "عطلة الخريف",
    "maqta": "عطلة الخريف من 28 أكتوبر إلى الإثنين 2 نوفمبر 2026",
    "mawrid": "عطلة الخريف من 28 أكتوبر إلى الإثنين 2 نوفمبر 2026",
    "learningContent": "عطلة الخريف من 28 أكتوبر إلى الإثنين 2 نوفمبر 2026",
    "allocatedHours": 0,
    "status": "pending"
  },
  {
    "id": "1am-w9",
    "level": "1am",
    "trimester": 1,
    "month": "نوفمبر",
    "weekNumber": 9,
    "weekDates": "02-05",
    "midan": "الإنسان والصحة",
    "maqta": "I",
    "mawrid": "3 الرواتب الغذائية والتوازن الغذائي",
    "learningContent": "3- الرواتب الغذائية والتوازن الغذائي:\nنشاط 1 يحدد - الحاجيات الغذائية للعضوية على أساس دورها\nنشاط 2 يستنتج العوامل التي تتحكم في تغير الحاجيات الغذائية\n- الفرض المحروس الأول",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w10",
    "level": "1am",
    "trimester": 1,
    "month": "نوفمبر",
    "weekNumber": 10,
    "weekDates": "08-12",
    "midan": "الإنسان والصحة",
    "maqta": "I",
    "mawrid": "3",
    "learningContent": "نشاط 3 يحل وضعية إدماج تخص التوازن الغذائي.\n- تصحيح الفرض المحروس الأول",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w11",
    "level": "1am",
    "trimester": 1,
    "month": "نوفمبر",
    "weekNumber": 11,
    "weekDates": "15-19",
    "midan": "الإنسان والصحة",
    "maqta": "II التغذية عند النبات الأخضر",
    "mawrid": "1 أغذية النبات الأخضر",
    "learningContent": "طرح وضعية مشكلة انطلاقية: ... طرح وضعيات تعلم الموارد\n- الحاجات الغذائية عند النبات الأخضر\n- نشاط 1 يقترح بروتوكولا تجريبيا أو يحلل نتائج تجريبية: الحاجات الغذائية الضرورية لنمو النبات الأخضر",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w12",
    "level": "1am",
    "trimester": 1,
    "month": "نوفمبر",
    "weekNumber": 12,
    "weekDates": "22-26",
    "midan": "الإنسان والصحة",
    "maqta": "II",
    "mawrid": "1",
    "learningContent": "نشاط 2 يستخرج - العناصر الأساسية في محلول كنوب\n- يستنتج عواقب التفريط والافراط في العناصر المعدنية للنبات الأخضر\n- نشاط 3 يقترح بروتوكولا تجريبيا أو يحلل نتائج تجريبية حول (مقر امتصاص المحلول المعدني)",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w13",
    "level": "1am",
    "trimester": 1,
    "month": "ديسمبر",
    "weekNumber": 13,
    "weekDates": "29-03",
    "midan": "الإنسان والصحة",
    "maqta": "II",
    "mawrid": "2 التركيب الضوئي",
    "learningContent": "المبادلات الغازية اليخضورية عند النبات الأخضر ومقرها\n- نشاط 1 يحلل - نتائج تجريبية تظهر حدوث المبادلات الغازية اليخضورية عند النبات الأخضر ومقرها.",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w14",
    "level": "1am",
    "trimester": 1,
    "month": "ديسمبر",
    "weekNumber": 14,
    "weekDates": "06-10",
    "midan": "اختبارات",
    "maqta": "اختبارات الفصل الأول من 6 إلى 10 ديسمبر 2026",
    "mawrid": "اختبارات الفصل الأول من 6 إلى 10 ديسمبر 2026",
    "learningContent": "اختبارات الفصل الأول من 6 إلى 10 ديسمبر 2026",
    "allocatedHours": 0,
    "status": "pending"
  },
  {
    "id": "1am-w15",
    "level": "1am",
    "trimester": 1,
    "month": "ديسمبر",
    "weekNumber": 15,
    "weekDates": "13-17",
    "midan": "الإنسان والصحة",
    "maqta": "II",
    "mawrid": "3 الاعتناء بالنبات الأخضر كمنتج للمادة العضوية",
    "learningContent": "- تصحيح الإختبار الأول\n- 3- الاعتناء - بالنبات الأخضر كمنتج للمادة العضوية\n- نشاط 1 يحلل - نتائج تطبيقات فلاحية لإكثار الإنتاج النباتي بالتحكم في شروط التركيب الضوئي",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w16",
    "level": "1am",
    "trimester": 1,
    "month": "ديسمبر",
    "weekNumber": 16,
    "weekDates": "17 ديسمبر - 03 جانفي",
    "midan": "عطلة الشتاء",
    "maqta": "عطلة الشتاء من الخميس 17 ديسمبر 2026 إلى الأحد 3 جانفي 2027",
    "mawrid": "عطلة الشتاء من الخميس 17 ديسمبر 2026 إلى الأحد 3 جانفي 2027",
    "learningContent": "عطلة الشتاء من الخميس 17 ديسمبر 2026 إلى الأحد 3 جانفي 2027",
    "allocatedHours": 0,
    "status": "pending"
  },
  {
    "id": "1am-w17",
    "level": "1am",
    "trimester": 2,
    "month": "جانفي",
    "weekNumber": 17,
    "weekDates": "04-08",
    "midan": "الإنسان والصحة",
    "maqta": "II التغذية عند النبات الأخضر",
    "mawrid": "2 التركيب الضوئي (تابع)",
    "learningContent": "نشاط 2 يحلل - نتائج تجريبية تظهر تدخل اليخضور والضوء في التركيب الضوئي\nنشاط 3 ينجز - حوصلة (رسم تخطيطي للتركيب الضوئي ومعادلته)",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w18",
    "level": "1am",
    "trimester": 2,
    "month": "جانفي",
    "weekNumber": 18,
    "weekDates": "11-15",
    "midan": "الإنسان والصحة",
    "maqta": "II",
    "mawrid": "3 الاعتناء بالنبات الأخضر",
    "learningContent": "نشاط 1 يحلل - نتائج تطبيقات فلاحية لإكثار الإنتاج النباتي بالتحكم في شروط التركيب الضوئي (تابع)\nنشاط 2 ينجز - بطاقة تقنية للاعتناء بالنبات الأخضر",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w19",
    "level": "1am",
    "trimester": 2,
    "month": "جانفي",
    "weekNumber": 19,
    "weekDates": "18-22",
    "midan": "الإنسان والصحة",
    "maqta": "II",
    "mawrid": "إدماج",
    "learningContent": "- حل وضعية إدماج تخص التغذية عند النبات الأخضر\n- تقويم المقطع الثاني",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w20",
    "level": "1am",
    "trimester": 2,
    "month": "جانفي",
    "weekNumber": 20,
    "weekDates": "25-29",
    "midan": "الإنسان والصحة",
    "maqta": "III التنفس عند الإنسان والنبات",
    "mawrid": "",
    "learningContent": "- عرض وضعية الانطلاق ومناقشتها",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w21",
    "level": "1am",
    "trimester": 2,
    "month": "فيفري",
    "weekNumber": 21,
    "weekDates": "01-05",
    "midan": "الإنسان والصحة",
    "maqta": "III",
    "mawrid": "1 المبادلات الغازية التنفسية ومقرها",
    "learningContent": "1- المبادلات الغازية التنفسية ومقرها:\nنشاط 1 يحلل - نتائج تجريبية تظهر حركات التنفس وآليتها\nنشاط 2 يستخرج - مقر المبادلات الغازية التنفسية على مستوى الرئة (الأسناخ)",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w22",
    "level": "1am",
    "trimester": 2,
    "month": "فيفري",
    "weekNumber": 22,
    "weekDates": "08-12",
    "midan": "الإنسان والصحة",
    "maqta": "III",
    "mawrid": "1",
    "learningContent": "نشاط 3 ينجز - رسما تخطيطيا لمقطع في الرئة يوضح مقر المبادلات\nنشاط 4 يحلل - نتائج تجريبية للمبادلات الغازية التنفسية بين هواء الأسناخ والدم",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w23",
    "level": "1am",
    "trimester": 2,
    "month": "فيفري",
    "weekNumber": 23,
    "weekDates": "15-19",
    "midan": "الإنسان والصحة",
    "maqta": "III",
    "mawrid": "2 التنفس عند النبات الأخضر",
    "learningContent": "2- التنفس عند النبات الأخضر:\nنشاط 1 يقترح بروتوكولا تجريبيا أو يحلل نتائج تجريبية تظهر حدوث التنفس عند النبات الأخضر\nنشاط 2 يستنتج - مقر المبادلات الغازية التنفسية عند النبات",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w24",
    "level": "1am",
    "trimester": 2,
    "month": "فيفري",
    "weekNumber": 24,
    "weekDates": "22-26",
    "midan": "الإنسان والصحة",
    "maqta": "III",
    "mawrid": "3 القواعد الصحية للتنفس",
    "learningContent": "3- القواعد الصحية للتنفس:\nنشاط 1 يقارن - بين تركيب هواء الشهيق والزفير\nنشاط 2 يستخرج - القواعد الصحية للتنفس من خلال تحليل وثائق\n- الفرض المحروس الثاني",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w25",
    "level": "1am",
    "trimester": 2,
    "month": "مارس",
    "weekNumber": 25,
    "weekDates": "01-05",
    "midan": "الإنسان والصحة",
    "maqta": "III",
    "mawrid": "إدماج",
    "learningContent": "- حل وضعية إدماج تخص التنفس\n- تصحيح الفرض المحروس الثاني\n- تقويم المقطع الثالث",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w26",
    "level": "1am",
    "trimester": 2,
    "month": "مارس",
    "weekNumber": 26,
    "weekDates": "07-11",
    "midan": "اختبارات",
    "maqta": "اختبارات الفصل الثاني من 7 إلى 11 مارس 2027",
    "mawrid": "اختبارات الفصل الثاني من 7 إلى 11 مارس 2027",
    "learningContent": "اختبارات الفصل الثاني من 7 إلى 11 مارس 2027",
    "allocatedHours": 0,
    "status": "pending"
  },
  {
    "id": "1am-w27",
    "level": "1am",
    "trimester": 2,
    "month": "مارس",
    "weekNumber": 27,
    "weekDates": "14-18",
    "midan": "الإنسان والصحة",
    "maqta": "IV انتقال النسغ عند النبات",
    "mawrid": "",
    "learningContent": "- تصحيح الاختبار الثاني\n- عرض وضعية الانطلاق ومناقشتها",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w28",
    "level": "1am",
    "trimester": 2,
    "month": "مارس",
    "weekNumber": 28,
    "weekDates": "21-25",
    "midan": "الإنسان والصحة",
    "maqta": "IV",
    "mawrid": "1 مقر وآلية انتقال النسغ",
    "learningContent": "1- مقر وآلية انتقال النسغ:\nنشاط 1 يحلل - نتائج تجريبية تظهر مقر انتقال النسغ (النسغ الناقص والكامل) وآليته\nنشاط 2 يستنتج - العلاقة بين النسغ والتركيب الضوئي والتنفس",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w29",
    "level": "1am",
    "trimester": 2,
    "month": "مارس",
    "weekNumber": 29,
    "weekDates": "31 مارس - 11 أفريل",
    "midan": "عطلة الربيع",
    "maqta": "عطلة الربيع من 31 مارس إلى الأحد 11 أفريل 2027",
    "mawrid": "عطلة الربيع من 31 مارس إلى الأحد 11 أفريل 2027",
    "learningContent": "عطلة الربيع من 31 مارس إلى الأحد 11 أفريل 2027",
    "allocatedHours": 0,
    "status": "pending"
  },
  {
    "id": "1am-w30",
    "level": "1am",
    "trimester": 3,
    "month": "أفريل",
    "weekNumber": 30,
    "weekDates": "12-16",
    "midan": "الإنسان والصحة",
    "maqta": "IV",
    "mawrid": "1 (تابع)",
    "learningContent": "نشاط 3 ينجز - رسما تخطيطيا يوضح مسار النسغ في النبات\nنشاط 4 يحلل - وثائق تظهر دور النسغ الناقص والكامل",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w31",
    "level": "1am",
    "trimester": 3,
    "month": "أفريل",
    "weekNumber": 31,
    "weekDates": "19-23",
    "midan": "الإنسان والصحة",
    "maqta": "IV",
    "mawrid": "2 دور النسغ",
    "learningContent": "2- دور النسغ في تزويد العضوية بالمادة والطاقة:\nنشاط 1 يحلل - وثائق تظهر دور النسغ الناقص والكامل في نمو النبات\n- الفرض المحروس الثالث",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w32",
    "level": "1am",
    "trimester": 3,
    "month": "أفريل",
    "weekNumber": 32,
    "weekDates": "26-30",
    "midan": "الإنسان والصحة",
    "maqta": "IV",
    "mawrid": "إدماج + تقويم",
    "learningContent": "- تصحيح الفرض المحروس الثالث\n- إدماج كلي للمقطع الرابع + تقويم المقطع\n- الاعتناء بالنباتات كمنتجة للمادة العضوية (بطاقة تقنية)",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w33",
    "level": "1am",
    "trimester": 3,
    "month": "ماي",
    "weekNumber": 33,
    "weekDates": "03-07",
    "midan": "الإنسان والصحة",
    "maqta": "V التنوع البيولوجي والتوازن البيئي",
    "mawrid": "",
    "learningContent": "- عرض وضعية الانطلاق ومناقشتها",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w34",
    "level": "1am",
    "trimester": 3,
    "month": "ماي",
    "weekNumber": 34,
    "weekDates": "03-07",
    "midan": "الإنسان والصحة",
    "maqta": "V",
    "mawrid": "1 مظاهر التنوع البيولوجي",
    "learningContent": "1- مظاهر التنوع البيولوجي:\nنشاط 1 يستخرج - مظاهر التنوع البيولوجي من خلال تحليل وثائق وصور\nنشاط 2 يصنف - الكائنات الحية حسب وسط عيشها وطريقة عيشها",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w35",
    "level": "1am",
    "trimester": 3,
    "month": "ماي",
    "weekNumber": 35,
    "weekDates": "10-14",
    "midan": "الإنسان والصحة",
    "maqta": "V",
    "mawrid": "1",
    "learningContent": "نشاط 3 ينجز - جدول تصنيف للكائنات الحية في وسطين مختلفين (بري ومائي)\nنشاط 4 يستنتج - مفهوم النظام البيئي",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w36",
    "level": "1am",
    "trimester": 3,
    "month": "ماي",
    "weekNumber": 36,
    "weekDates": "17-21",
    "midan": "الإنسان والصحة",
    "maqta": "V",
    "mawrid": "2 العلاقات القائمة بين الكائنات الحية",
    "learningContent": "2- العلاقات القائمة بين الكائنات الحية:\nنشاط 1 يحلل - العلاقات الغذائية (سلسلة وشبكة غذائية)\nنشاط 2 يستنتج - العلاقات الأخرى (تعاون، تطفل، افتراس)\n- حل وضعية إدماج تخص التنوع البيولوجي",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w37",
    "level": "1am",
    "trimester": 3,
    "month": "ماي",
    "weekNumber": 37,
    "weekDates": "23-27",
    "midan": "اختبارات",
    "maqta": "اختبارات الفصل الثالث من 23 إلى 27 ماي 2027",
    "mawrid": "اختبارات الفصل الثالث من 23 إلى 27 ماي 2027",
    "learningContent": "اختبارات الفصل الثالث من 23 إلى 27 ماي 2027",
    "allocatedHours": 0,
    "status": "pending"
  },
  {
    "id": "1am-w38",
    "level": "1am",
    "trimester": 3,
    "month": "جوان",
    "weekNumber": 38,
    "weekDates": "31 ماي - 04 جوان",
    "midan": "الإنسان والصحة",
    "maqta": "V",
    "mawrid": "حماية المحيط",
    "learningContent": "- تصحيح الاختبار الثالث\n1- أخطار تهدد التنوع البيولوجي:\nنشاط 1 يحلل - وثائق تظهر أخطار طبيعية وبشرية تهدد التنوع\n2- حماية المحيط:\nنشاط 1 يقترح - حلولا لحماية المحيط والمحافظة على التنوع البيولوجي (مطوية توعوية)",
    "allocatedHours": 2,
    "status": "pending"
  },
  {
    "id": "1am-w39",
    "level": "1am",
    "trimester": 3,
    "month": "جوان",
    "weekNumber": 39,
    "weekDates": "07-11",
    "midan": "الإنسان والصحة",
    "maqta": "إدماج كلي",
    "mawrid": "مراجعة شاملة",
    "learningContent": "- إدماج كلي للمقاطع التعلمية + معالجة بيداغوجية\n- مراجعة شاملة وتحضير للسنة الثانية متوسط",
    "allocatedHours": 2,
    "status": "pending"
  }
];

const finalArr = [...data1am, ...filteredArr];

const newFileContent = `import { AnnualDistributionItem } from '../types';\n\nexport const ANNUAL_DISTRIBUTIONS: AnnualDistributionItem[] = ${JSON.stringify(finalArr, null, 2)};\n`;

fs.writeFileSync('src/data/annualDistributionData.ts', newFileContent);
console.log('Patched 1AM successfully.');
