const fs = require('fs');

const data = [
  { id: '1am-t1-w1', level: '1am', trimester: 1, month: 'سبتمبر', weekNumber: 1, midan: 'الإنسان والصحة', maqta: 'التقويم التشخيصي', mawrid: 'تقويم تشخيصي', learningContent: 'الحصة 1: استقبال التلاميذ؛ تعارف و تقويم تشخيصي\nالحصة 2: عرض الوضعية الانطلاقية الشاملة ومناقشتها وطرح التساؤلات حولها', allocatedHours: 2, status: 'pending' },
  { id: '1am-t1-w2', level: '1am', trimester: 1, month: 'سبتمبر', weekNumber: 2, midan: 'الإنسان والصحة', maqta: 'التقويم التشخيصي', mawrid: 'معالجة بيداغوجية', learningContent: 'الحصة 1: الكفاءة الأولى: حفظ الصحة المعايير: 3، 4، 5 + الكفاءة الثانية: حماية المحيط المعايير: 3، 4، 5\nالحصة 2: عرض وضعية الانطلاق ومناقشتها', allocatedHours: 2, status: 'pending' },
  { id: '1am-t1-w3', level: '1am', trimester: 1, month: 'أكتوبر', weekNumber: 3, midan: 'الإنسان والصحة', maqta: 'المقطع I: التغذية عند الإنسان', mawrid: '1 مصدر الأغذية وتركيبها', learningContent: 'الحصة 1: 1- مصدر الأغذية وتركيبها: نشاط 1 يكشف - تجريبيا مصدر الأغذية أو يحلل نتائج تجريبية.\nالحصة 2: نشاط 2 يقارن - تركيب بعض الأغذية (يكشف تجريبيا مركبات الغذاء) + نشاط 3 ينجز - حوصلة لمصدر الأغذية وتركيبها (مخطط تلخيصي أو نص)', allocatedHours: 2, status: 'pending' },
  { id: '1am-t1-w4', level: '1am', trimester: 1, month: 'أكتوبر', weekNumber: 4, midan: 'الإنسان والصحة', maqta: 'المقطع I: التغذية عند الإنسان', mawrid: '2 دور الأغذية في الجسم', learningContent: 'الحصة 1: 2 - دور الأغذية في الجسم: نشاط 1 يستخرج - العلاقة بين أعراض بعض أمراض سوء التغذية ومميزات الغذاء المستهلك.\nالحصة 2: نشاط 2 يلخص - دور الأغذية في العضوية.', allocatedHours: 2, notes: 'عطلة الخريف من 28 أكتوبر إلى 2 نوفمبر 2026', status: 'pending' },
  { id: '1am-t1-w5', level: '1am', trimester: 1, month: 'نوفمبر', weekNumber: 5, midan: 'الإنسان والصحة', maqta: 'المقطع I: التغذية عند الإنسان', mawrid: '3 الرواتب الغذائية والتوازن الغذائي', learningContent: 'الحصة 1: 3 - الرواتب الغذائية والتوازن الغذائي: نشاط 1 يحدد - الحاجيات الغذائية للعضوية على أساس دورها.\nالحصة 2: نشاط 2 يستنتج العوامل التي تتحكم في تغير الحاجيات الغذائية + الفرض المحروس الأول.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t1-w6', level: '1am', trimester: 1, month: 'نوفمبر', weekNumber: 6, midan: 'الإنسان والصحة', maqta: 'المقطع I: التغذية عند الإنسان', mawrid: '3 الرواتب الغذائية والتوازن الغذائي', learningContent: 'الحصة 1: نشاط 3 يحل وضعية إدماج تخص التوازن الغذائي.\nالحصة 2: تصحيح الفرض المحروس الأول.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t1-w7', level: '1am', trimester: 1, month: 'نوفمبر', weekNumber: 7, midan: 'الإنسان والمحيط', maqta: 'المقطع II: التغذية عند النبات الأخضر', mawrid: '1 أغذية النبات الأخضر', learningContent: 'الحصة 1: طرح وضعية مشكلة انطلاقية: ... طرح وضعيات تعلم الموارد.\nالحصة 2: الحاجات الغذائية عند النبات الأخضر: نشاط 1 يقترح بروتوكولا تجريبيا أو يحلل نتائج تجريبية: الحاجات الغذائية الضرورية لنمو النبات الأخضر.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t1-w8', level: '1am', trimester: 1, month: 'نوفمبر', weekNumber: 8, midan: 'الإنسان والمحيط', maqta: 'المقطع II: التغذية عند النبات الأخضر', mawrid: '1 أغذية النبات الأخضر', learningContent: 'الحصة 1: نشاط 2 يستخرج - العناصر الأساسية في محلول كنوب يستنتج عواقب التفريط والافراط في العناصر المعدنية للنبات الأخضر.\nالحصة 2: نشاط 3 يقترح بروتوكولا تجريبيا أو يحلل نتائج تجريبية حول (مقرامتصاص المحلول المعدني).', allocatedHours: 2, status: 'pending' },
  { id: '1am-t1-w9', level: '1am', trimester: 1, month: 'ديسمبر', weekNumber: 9, midan: 'الإنسان والمحيط', maqta: 'المقطع II: التغذية عند النبات الأخضر', mawrid: '2 التركيب الضوئي', learningContent: 'الحصة 1: المبادلات الغازية اليخضورية عند النبات الأخضر ومقرها.\nالحصة 2: نشاط 1 يحلل - نتائج تجريبية تظهر حدوث المبادلات الغازية اليخضورية عند النبات الأخضر ومقرها.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t1-w10', level: '1am', trimester: 1, month: 'ديسمبر', weekNumber: 10, midan: 'الإنسان والمحيط', maqta: 'تقويم وإدماج', mawrid: 'اختبارات الفصل الأول', learningContent: 'الحصة 1: اختبارات الفصل الأول من 6 إلى 10 ديسمبر 2026.\nالحصة 2: اختبارات الفصل الأول من 6 إلى 10 ديسمبر 2026.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t1-w11', level: '1am', trimester: 1, month: 'ديسمبر', weekNumber: 11, midan: 'الإنسان والمحيط', maqta: 'المقطع II: التغذية عند النبات الأخضر', mawrid: '3 الاعتناء بالنبات الأخضر كمنتج للمادة', learningContent: 'الحصة 1: تصحيح الإختبار الأول.\nالحصة 2: 3- الاعتناء بالنبات الاخضر كمنتج للمادة العضوية: نشاط 1 يحلل - نتائج تطبيقات فلاحية لإكثار الإنتاج النباتي بالتحكم في شروط التركيب الضوئي.', allocatedHours: 2, notes: 'عطلة الشتاء من الخميس 17 ديسمبر 2026 إلى الأحد 3 جانفي 2027', status: 'pending' },
  { id: '1am-t2-w12', level: '1am', trimester: 2, month: 'جانفي', weekNumber: 12, midan: 'الإنسان والمحيط', maqta: 'المقطع II: التغذية عند النبات الأخضر', mawrid: '4 انتقال النسغ', learningContent: 'الحصة 1: نشاط 1 يحدد - مقر انتقال النسغ الخام في النبات الاخضر + نشاط 2 ينجز تجربة أو يفسر - نتائج تجريبية تبرز دور النتح.\nالحصة 2: نشاط 3 ينمذج - مسار النسغ في النبات الأخضر أو يكتب فقرة + طرح وضعية إدماج الموارد التي تم بناءها + معالجة بيداغوجية محتملة.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t2-w13', level: '1am', trimester: 2, month: 'جانفي', weekNumber: 13, midan: 'الإنسان والصحة', maqta: 'المقطع III: التحصل على الطاقة عند الإنسان', mawrid: '1 المبادلات الغازية التنفسية عند الإنسان', learningContent: 'الحصة 1: طرح وضعية مشكل انطلاقية: طرح وضعيات تعلم الموارد التالية.\nالحصة 2: 1- المبادلات الغازية - التنفسية و مقرها: نشاط 1 يحدد - مقر المبادلات الغازية التنفسية عند الانسان + نشاط 2 يستخرج - مميزات السنخ الرئوي التي تجعل منه سطح تبادل.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t2-w14', level: '1am', trimester: 2, month: 'جانفي', weekNumber: 14, midan: 'الإنسان والصحة', maqta: 'المقطع III: التحصل على الطاقة عند الإنسان', mawrid: '2 المعنى البيولوجي للتنفس', learningContent: 'الحصة 1: 2-التنفس مصدر للطاقة: نشاط 1 يفسر - زيادة استهلاك الغذاء والأكسجين عند زيادة نشاط العضوية لبناء المعنى البيولوجي للتنفس.\nالحصة 2: الفرض المحروس الثاني.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t2-w15', level: '1am', trimester: 2, month: 'فيفري', weekNumber: 15, midan: 'الإنسان والصحة', maqta: 'المقطع III: التحصل على الطاقة عند الإنسان', mawrid: '3 قواعد التنفس الصحي', learningContent: 'الحصة 1: 3-قواعد التنفس الصحي: نشاط 1 يناقش - وضعيات اختلال وظيفة التنفس لإبراز أهميتها الصحية.\nالحصة 2: تصحيح الفرض المحروس الثاني.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t2-w16', level: '1am', trimester: 2, month: 'فيفري', weekNumber: 16, midan: 'الإنسان والمحيط', maqta: 'المقطع IV: التحصل على الطاقة عند النبات الأخضر', mawrid: '1 المبادلات الغازية التنفسية ومقرها', learningContent: 'الحصة 1: طرح وضعية مشكل انطلاقية: ... طرح وضعيات تعلم الموارد التالية.\nالحصة 2: نشاط 1 يحدد مقر - المبادلات إما بإنجاز تجارب أو بتحليل نتائج تجريبية + نشاط 2 يفحص - مجهريا بشرة عضو نباتي أو يستغل وثائق هادفة.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t2-w17', level: '1am', trimester: 2, month: 'فيفري', weekNumber: 17, midan: 'الإنسان والمحيط', maqta: 'المقطع IV: التحصل على الطاقة عند النبات الأخضر', mawrid: '2 تعريف تنفس النبات كعملية تحصل على الطاقة', learningContent: 'الحصة 1: 2 تعريف تنفس النبات كعملية تحصل على الطاقة.\nالحصة 2: نشاط 1 يضع علاقة سببية بين زيادة استهلاك الغذاء وغاز O2 والنشاط الفيزيولوجي للنبات لبناء المعنى البيولوجي للتنفس.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t2-w18', level: '1am', trimester: 2, month: 'فيفري', weekNumber: 18, midan: 'الإنسان والمحيط', maqta: 'المقطع IV: التحصل على الطاقة عند النبات الأخضر', mawrid: '3 تعريف التخمر كنمط آخر للتحصل على الطاقة', learningContent: 'الحصة 1: 3 تعريف التخمر كنمط آخر للتحصل على الطاقة: نشاط 1 يعلل لجوء بعض الكائنات الحية للتخمر + نشاط 2 يستخرج - الفرق بين التنفس والتخمر.\nالحصة 2: طرح وضعية إدماج الموارد التي تم بناءها + معالجة بيداغوجية محتملة.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t2-w19', level: '1am', trimester: 2, month: 'مارس', weekNumber: 19, midan: 'الإنسان والصحة', maqta: 'المقطع V: الإطراح عند الإنسان', mawrid: '1 تعريف الإطراح ودوره في ثبات توازن الوسط داخلي', learningContent: 'الحصة 1: طرح وضعية مشكل انطلاقية: ... طرح وضعيات تعلم الموارد التالية + 1 تعريف الإطراح ودوره في ثبات توازن الوسط داخلي.\nالحصة 2: نشاط 1 يقارن - بين تركيب البول والدم والعرق لبناء مفهوم الاطراح + نشاط 2 يصف - أعضاء الإطراح ويصف بنية الكلية والجلد ويحدد دورهما في الإطراح.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t2-w20', level: '1am', trimester: 2, month: 'مارس', weekNumber: 20, midan: 'الإنسان والصحة', maqta: 'تقويم وإدماج', mawrid: 'اختبارات الفصل الثاني', learningContent: 'الحصة 1: اختبارات الفصل الثاني من 7 إلى 11 مارس 2027.\nالحصة 2: اختبارات الفصل الثاني من 7 إلى 11 مارس 2027.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t2-w21', level: '1am', trimester: 2, month: 'مارس', weekNumber: 21, midan: 'الإنسان والصحة', maqta: 'المقطع V: الإطراح عند الإنسان', mawrid: '2 القواعد الصحية للاطراح', learningContent: 'الحصة 1: تصحيح الإختبار الثاني + 2 القواعد الصحية للاطراح: نشاط 1 يناقش - وضعيات لحالات مرضية تخص الإنتان البولي أو تشكل الحصى في الكلى لاستخراج أهم القواعد الصحية للاطراح.\nالحصة 2: طرح وضعية إدماج الموارد التي تم بناءها + معالجة بيداغوجية محتملة.', allocatedHours: 2, notes: 'عطلة الربيع من الخميس 18 مارس إلى الأحد 4 أفريل 2027', status: 'pending' },
  { id: '1am-t3-w22', level: '1am', trimester: 3, month: 'أفريل', weekNumber: 22, midan: 'الإنسان والصحة', maqta: 'المقطع VI: التكاثر عند الإنسان', mawrid: '1 الأجهزة التكاثرية', learningContent: 'الحصة 1: 1 - البنية التشريحية للأجهزة التكاثرية عند الإنسان: نشاط:1 - يميز المجاري التناسلية والمناسل.\nالحصة 2: نشاط:2 - يبرز دور كل من المبيض والخصية بتحليل نتائج تجريبية.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t3-w23', level: '1am', trimester: 3, month: 'أفريل', weekNumber: 23, midan: 'الإنسان والصحة', maqta: 'المقطع VI: التكاثر عند الإنسان', mawrid: '2 الإلقاح و شروطه', learningContent: 'الحصة 1: 2 - الالقاح وشروطه: نشاط : - يستخرج مفهوم الالقاح.\nالحصة 2: نشاط 1 - يحدد شروط حدوث الالقاح.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t3-w24', level: '1am', trimester: 3, month: 'أفريل', weekNumber: 24, midan: 'الإنسان والصحة', maqta: 'المقطع VI: التكاثر عند الإنسان', mawrid: '3 القواعد الصحية للتكاثر', learningContent: 'الحصة 1: 3- القواعد الصحية للتكاثر: نشاط 1 - انجاز بحوث موجهة تخص الصحة الجنسية.\nالحصة 2: الفرض المحروس الثالث + وضعية انطلاق المقطع الخامس.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t3-w25', level: '1am', trimester: 3, month: 'أفريل', weekNumber: 25, midan: 'الإنسان والمحيط', maqta: 'المقطع VII: التكاثر عند النباتات ذات الأزهار', mawrid: '1 الجهاز التكاثري عند النبات الزهري', learningContent: 'الحصة 1: البنية التشريحية للأجهزة التكاثرية عند النبات الزهري: نشاط 1 : يقارن بين زهرة ذكرية وأخرى انثوية لإبراز الجنسية.\nالحصة 2: نشاط 2 : - يحدد دور كل من السداة والمدقة + تصحيح الفرض المحروس الثالث.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t3-w26', level: '1am', trimester: 3, month: 'ماي', weekNumber: 26, midan: 'الإنسان والمحيط', maqta: 'المقطع VII: التكاثر عند النباتات ذات الأزهار', mawrid: '1 الالقاح وشروطه', learningContent: 'الحصة 1: الالقاح وشروطه.\nالحصة 2: نشاط 1 : - يستخرج مميزات التكاثر الجنسي عند النباتات ذات الأزهار.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t3-w27', level: '1am', trimester: 3, month: 'ماي', weekNumber: 27, midan: 'الإنسان والمحيط', maqta: 'المقطع VIII: الخلية', mawrid: '1 الخلية', learningContent: 'الحصة 1: نشاط 1 : - يفحص مجهريا نسيج حيواني وآخر نباتي.\nالحصة 2: نشاط 2 : - يستخرج المكونات الأساسية المشتركة للخلية فحص مجهري.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t3-w28', level: '1am', trimester: 3, month: 'ماي', weekNumber: 28, midan: 'تقويم وإدماج', maqta: 'إدماج كلي للمقطع 7 و 8', mawrid: 'حصة ادماج كلي', learningContent: 'الحصة 1: حصة ادماج كلي للمقطع 7 و 8.\nالحصة 2: حل وضعيات مشكلة تقويمية.', allocatedHours: 2, status: 'pending' },
  { id: '1am-t3-w29', level: '1am', trimester: 3, month: 'ماي', weekNumber: 29, midan: 'تقويم وإدماج', maqta: 'اختبارات الفصل الثالث', mawrid: 'اختبارات الفصل الثالث', learningContent: 'الحصة 1: اختبارات الفصل الثالث من 17 إلى 21 ماي 2027.\nالحصة 2: اختبارات الفصل الثالث من 17 إلى 21 ماي 2027.', allocatedHours: 2, status: 'pending' }
];

let fileContent = fs.readFileSync('src/data/annualDistributionData.ts', 'utf8');
const startIndex = fileContent.indexOf('  // ==========================================\n  // 1AM - السنة الأولى متوسط');
const endIndex = fileContent.indexOf('  // 2AM - السنة الثانية متوسط');

if (startIndex !== -1 && endIndex !== -1) {
  const arrStr = data.map(item => {
    return `  {
    id: ${JSON.stringify(item.id)},
    level: ${JSON.stringify(item.level)},
    trimester: ${JSON.stringify(item.trimester)},
    month: ${JSON.stringify(item.month)},
    weekNumber: ${item.weekNumber},
    midan: ${JSON.stringify(item.midan)},
    maqta: ${JSON.stringify(item.maqta)},
    mawrid: ${JSON.stringify(item.mawrid)},
    learningContent: ${JSON.stringify(item.learningContent)}` +
    (item.notes ? `,\n    notes: ${JSON.stringify(item.notes)}` : '') +
    `,\n    allocatedHours: ${item.allocatedHours},
    status: ${JSON.stringify(item.status)}
  },`;
  }).join('\n');

  const newContent = fileContent.substring(0, startIndex) + 
    '  // ==========================================\n' +
    '  // 1AM - السنة الأولى متوسط\n' +
    '  // ==========================================\n' +
    arrStr + '\n' +
    fileContent.substring(endIndex);
    
  fs.writeFileSync('src/data/annualDistributionData.ts', newContent);
  console.log('Successfully updated 1AM data with Hissa 1 and Hissa 2 using exact text and properly escaped newlines.');
} else {
  console.error('Could not find markers for 1AM and 2AM.');
}
